import dynamic from "next/dynamic";
import { ComponentType } from "react";

export const toolComponents: Record<string, ComponentType> = {
  "json-formatter": dynamic(() => import("./json-formatter")),
  "json-validator": dynamic(() => import("./json-validator")),
  "ai-coding-prompt-generator": dynamic(() => import("./ai-coding-prompt-generator")),
  "ai-bug-fix-prompt-generator": dynamic(() => import("./ai-bug-fix-prompt-generator")),
  "meta-tag-generator": dynamic(() => import("./meta-tag-generator")),
  "robots-txt-generator": dynamic(() => import("./robots-txt-generator")),
  "open-graph-preview": dynamic(() => import("./open-graph-preview")),
  "xml-sitemap-generator": dynamic(() => import("./xml-sitemap-generator")),
  "utm-builder": dynamic(() => import("./utm-builder")),
  "json-minifier": dynamic(() => import("./json-minifier")),
  "base64-encode": dynamic(() => import("./base64-encode")),
  "base64-decode": dynamic(() => import("./base64-decode")),
  "url-encode": dynamic(() => import("./url-encode")),
  "url-decode": dynamic(() => import("./url-decode")),
  "jwt-decoder": dynamic(() => import("./jwt-decoder")),
  "uuid-generator": dynamic(() => import("./uuid-generator")),
  "timestamp-converter": dynamic(() => import("./timestamp-converter")),
  "regex-tester": dynamic(() => import("./regex-tester")),
  "cron-expression-generator": dynamic(() => import("./cron-expression-generator")),
  "hash-generator": dynamic(() => import("./hash-generator")),
  "password-generator": dynamic(() => import("./password-generator")),
  "text-diff-checker": dynamic(() => import("./text-diff-checker")),
  "qr-code-generator": dynamic(() => import("./qr-code-generator")),
  "sql-formatter": dynamic(() => import("./sql-formatter")),
  "html-formatter": dynamic(() => import("./html-formatter")),
  "css-formatter": dynamic(() => import("./css-formatter")),
  "javascript-formatter": dynamic(() => import("./javascript-formatter")),
  "markdown-previewer": dynamic(() => import("./markdown-previewer")),
  "slug-generator": dynamic(() => import("./slug-generator")),
  "word-counter": dynamic(() => import("./word-counter")),
  "case-converter": dynamic(() => import("./case-converter")),
  "color-converter": dynamic(() => import("./color-converter")),
  "svg-optimizer": dynamic(() => import("./svg-optimizer")),
  "image-to-base64": dynamic(() => import("./image-to-base64")),
  "css-gradient-generator": dynamic(() => import("./css-gradient-generator")),
  "dummy-json-generator": dynamic(() => import("./dummy-json-generator")),
  "csv-to-json-converter": dynamic(() => import("./csv-to-json-converter")),
  "bcrypt-generator": dynamic(() => import("./bcrypt-generator")),
  "ethereum-unit-converter": dynamic(() => import("./ethereum-unit-converter")),
  "base64-to-image": dynamic(() => import("./base64-to-image")),
  "base64-to-pdf": dynamic(() => import("./base64-to-pdf")),
  "file-to-base64": dynamic(() => import("./file-to-base64")),
  "sample-code-generator": dynamic(() => import("./sample-code-generator")),
};
