import { SITE_NAME } from "@/lib/constants";

export const metadata = {
  title: "Disclaimer",
  description: `Disclaimer for ${SITE_NAME}`,
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto space-y-6 prose dark:prose-invert">
      <h1 className="text-4xl font-extrabold tracking-tight">Disclaimer</h1>
      <p>Last updated: {new Date().toLocaleDateString()}</p>
      
      <h2>1. General Information</h2>
      <p>The information and tools provided by {SITE_NAME} (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) on our website are for general informational and utility purposes only. All information and tools on the site are provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or tool output on the site.</p>
      
      <h2>2. Tool Accuracy and Reliability</h2>
      <p>While we strive to provide accurate developer tools and AI prompts, {SITE_NAME} does not guarantee the correctness of the output generated by our tools. Users are solely responsible for verifying the results (such as formatted code, decoded tokens, generated prompts, or parsed data) before using them in production environments or making critical decisions.</p>
      
      <h2>3. External Links Disclaimer</h2>
      <p>The Site may contain links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us. We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the site.</p>
      
      <h2>4. No Professional Advice</h2>
      <p>The tools and content on {SITE_NAME} do not constitute professional advice. Any reliance you place on such information or tools is strictly at your own risk. We are not liable for any bugs, errors, security breaches, or data loss that may occur as a result of using output generated from our website.</p>
      
      <h2>5. Advertising Disclaimer</h2>
      <p>This site contains advertisements provided by Google AdSense and potentially other third-party ad networks. We do not necessarily endorse the products or services advertised. The presence of an ad does not imply an endorsement or recommendation.</p>
    </div>
  );
}
